order:
  - item: Cedar Basecamp Opps
  - item: overview
  - new_item: true
    item: Entities
    href: "/config/entities"
    icon: mdi:hexagon-multiple
  - new_item: true
    item: Devices
    href: "/config/devices/dashboard"
    icon: mdi:cellphone-link
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
  - new_item: true
    item: Add-Ons
    href: "/config/apps/installed"
    icon: mdi:plus-network

    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - item: config
    bottom: true
  - new_item: true
    item: Server Controls
    href: "/config/server_control"
    icon: mdi:server
    hide: true
  - item: activity
    bottom: true
    hide: true
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    hide: true
  - new_item: true
    item: developer tools
    name: Dev tools
    icon: mdi:tools
    href: "/config/developer-tools"
    bottom: true
  - new_item: true
    item: vs code
    name: VS Code
    bottom: true
    icon: mdi:microsoft-visual-studio-code
    href: "/app/a0d7b954_vscode"
  - item: hacs
    bottom: true
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media
    hide: true
# exceptions:
# - user:
#     - Jim Hawkins
#     - Long John Silver
#   order:
#     - new_item: true
#       item: Updates
#       href: "/config/updates"
#       icon: mdi:update
# - user: Palaus
#   extend_from: base
#   order:
#     - item: history
#       order: 11
#     - item: media
#       order: 12
